# Reviewers Like Me 
#### Amazon, Review Relevancy

## Do I trust your opinion?
Product and service reviews can sometimes be confusing.  Do you have any particularly discriminating friends?  When they tell you about a restaurant or a product, do you always temper their reaction – wondering if the oak overtones in their wine would actually ruin a meal?  On the other hand, do you have incredibly positive people in your life who rarely complain?  Are you skeptical of their "amazing, life changing" products?   When heeding the advice of friends and colleagues, a potential buyer has the context to better understand the review based on the person.  The buyer can then predict their own experience with the same product.  However, when reading through the dozens of reviews for popular products online at a major retailer like Amazon, it is easy to get bogged down in information overload with conflicting reviews.  Buying a product, sight unseen, is a risky proposition that consumers mitigate with other's opinions, but buyers wonder who are these reviewers and how much do my needs and opinions overlap with theirs?

## How do I build trust in your opinion? 
Amazon currently provides two review options: "All reviews " and "Verified Customer Reviews".  Amazon will provide a new feature with a link called "Reviewers Like Me".  It will help potential consumers who have reviewed Amazon products in the past navigate the confusing world of online reviewers.  
The "Reviewers Like Me" link will be powered by a new algorithm developed at UC Berkeley's MIDS program.  Amazon will cluster customers who have submitted a significant amount of reviews based on multiple variables for the reviewer and product category.  Some of the variables used in the algorithm will include:       

1. Past Orders - Regardless of the reviews posted (if any), past order history can give the algorithm valuable information about a person.  For example, if a person orders many different kinds of outdoor items throughout all seasons and lives in a cold weather climate, their meaning of "warm" might be different from someone in a warmer climate.  Or if they buy the same running shoe every three months, it is likely that this customer is a high mileage runner. 
2. Demographics that prove to be predictive  
3. Self reported data - customers will have the ability to answer questions that would enable better review ranking.  This information is completely voluntary and will be based on the product category.     
4. Other reviewer's deviation from the average star review as compared with the current user's past review's deviation from the mean   
5. Key words used in reviews    
6. Marking "helpful" for past reviews    

All these variables will be weighted and used in the machine algorithm for predicting similar opinions for the current user.  Over time, the model will be recalibrated as the reviewer base changes.

A real world example: Susie is an amazon customer who buys a significant number of products and writes frequent reviews.  She is very particular about baby products and tends to review all baby items below the mean.  She is also an avid reader and tends to rate classic literature higher than the average.  Jane is another frequent Amazon customer and reviewer who is discriminating all around.  When she considers purchasing a baby item that Susie has reviewed, Susie's review will be included in the overall statistics from "Reviewers Like Me", and her review will be available.  However, if Jane moves onto classic literature- Susie's review will not appear in the “Reviewers Like Me” link since their opinions do not align for this product category.  Jane can always view "All Reviews" or "Amazon Verified Customer Reviews" as this will be helpful for products with sparsely reviewed products, but over time she will come to rely on the more helpful feature of “Reviewers Like Me”.


## How will this help Amazon?
This simple solution to wading through conflicting reviews will help Amazon in several ways:
1.  Consumers are more likely to buy based on trusted recommendations.  This trust will continue to build over time.   
2.  Return shipping costs will decrease as discriminating consumers make better decisions using only similarly discriminating reviews.
3.  This proposed feature will provide non-monetary incentives for consumers to review products.  If providing feedback means a consumer will be rewarded with better information on their next purchase, they will be more likely to provide thoughtful, honest feedback.  Their resulting reviews can in turn tell Amazon how well the algorithm is performing in a continuous feedback loop.  
4.  Understanding the customer better can also order the products better, so customers first see the products they are more likely to love based on reviews from other people with similar tastes.  
5.  This algorithm assumes that people will shift their spending dollars from a product that they wont likely love to a product that they will.  It is important that the Amazon site highlight other products with higher reviews when displaying a product with many negative reviews from "reviewers like the customer".

