 There is no "I" in team.

#### Keywords

Team Work
Empathy
Survey


## Giving Feedback is Hard

Employees today can expect to be a part of dozens of teams over their career.  What makes a team effective?  Skills?  Work Ethic?  Interpersonal skills?  As the world becomes increasingly connected, face to face communication decrease and the ability to always perceive non-verbal quees becomes more challenging.  Peers are often the best sources of feedback for employees, but it is sometimes challenging to offer candid feedback to a peer that you must continue working with and may even geniunely like.  

## UC Berkeley to the Rescue

The UC Berkeley Data Science program offers us the chance to work with peers from a variety of backgrounds that can offer us insights into our communication style and effectiveness if we can harness that feedback in a productive way. After every group project in every class, students will be required to submit results to an anonymous survey for each of their team members.  At the mid-term and end of term, compiled results will be shared.  These surveys will not be used in the grading process.  They are mereley a tool to make the entire cohort more effective at working with people from a range of backgrounds.  Here is the list of questions:

Project Team.    Please response on a scale of 1 (Strongly Disagree) to 5 (Strongly Agree).
1.  Did the team have the adequate skills to complete the project?
2.  Was the work evenly distributed?
3.  Did all team members contribute to the discussion equally?
4.  Did you personally feel safe to brainstorm ideas without judgment?
5.  Did your team produce a quality product? (scale 1:5)
6.  Would you want to work with this particular team again?


Individual.  Please response on a scale of 1 (Strongly Disagree) to 5 (Strongly Agree).
1.  Did John Smith contribute equally to the project?
2.  Did John Smith have the skills to complete the project?
3.  Did John Smith speak more (5) or less (1) than others?  (Score will actually be absolute distance from 3)
4.  Is John Smith a strong communicator?
5.  Did John Smith encourage (5) or discourage (0) your leads?
6.  Would you like to work with John Smith again?
7.  Would you seek out John Smith at the immersion?
8.  Any Additional Feedback:  (Free form text box)

Here are some example output graphs:








## Increased Self Awareness, Better Teams

Working well in teams is a necessary skill set for any data scientist.  This program gives us the opportunity to work with a variety of professionals from various backgrounds in a safe environment.  The opportunity to get valuable insights from a variety of teammates will help us become more effective at working with different types of people.  Having a consisent set of questions to answer about each other and consider on new project endeavors will help us understand trends over time and experiement with how to calibrate some of our natural tendencies.    
